"use client"

import { useRouter } from "next/navigation"
import { ProtectedRoute } from "@/components/auth/protected-route"
import { InvoiceForm } from "@/components/forms/invoice-form"
import { useCreateInvoice } from "@/lib/hooks/useInvoices"
import type { InvoiceFormData } from "@/components/forms/invoice-form"

export default function NewInvoicePage() {
  const router = useRouter()
  const createInvoice = useCreateInvoice()

  const handleSubmit = async (data: InvoiceFormData) => {
    // Transform form data to API format
    const payload = {
      customerId: data.customerId,
      lineItems: data.lineItems.map((item) => ({
        id: "", // Will be generated by backend
        description: item.description,
        quantity: item.quantity,
        unitPrice: item.unitPrice,
        amount: item.amount,
      })),
      dueDate: data.dueDate || "",
    }

    createInvoice.mutate(payload as any, {
      onSuccess: (invoice) => {
        router.push(`/invoices/${invoice.id}`)
      },
    })
  }

  return (
    <ProtectedRoute>
      <div className="container py-8">
        <div className="max-w-4xl mx-auto">
          <InvoiceForm onSubmit={handleSubmit} isLoading={createInvoice.isPending} />
        </div>
      </div>
    </ProtectedRoute>
  )
}

